class Commands:
    START_COMMAND = "start"
    HELP_COMMAND = "help"
    GET_VIDEOS_COMMAND = "get_videos"
    GET_PLAYLISTS = "get_playlists"
    GET_MEDIAS = "get_media"
    INSTALL_COMMAND = "install"
    FORMATS_INFO_COMMAND = "formats"
    CREATE_PLAYLIST = "create_playlist"
    ADD_MEDIA = "add_media"
